services:
  user-service:
    image: user-service
    container_name: user-service
    restart: always
    depends_on:
      - user-db
    environment:
      USER_DB_USER: admin
      USER_DB_PASSWORD: 1234
      USER_DB_HOST: user-db
      USER_DB_NAME: userdb
      USER_DB_PORT: 5432
    ports:
      - "8081:8081"

  user-db:
    image: postgres
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: userdb
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql

  notification-service:
    image: notification-service
    container_name: notification-service
    restart: always
    depends_on:
      - notification-db
    environment:
      NOTIFICATION_DB_USER: admin
      NOTIFICATION_DB_PASSWORD: 1234
      NOTIFICATION_DB_HOST: notification-db
      NOTIFICATION_DB_NAME: notificationdb
      NOTIFICATION_DB_PORT: 5432

  notification-db:
    image: postgres
    container_name: notification-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: notificationdb
      TZ: Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql

volumes:
  user_pgdata:
  notification_pgdata:
