services:
  user-db:
    image: postgres
    container_name: user_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: userdb
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - user_pgdata:/var/lib/postgresql

  notification-db:
    image: postgres
    container_name: notification_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: notificationdb
      TZ: Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql

volumes:
  user_pgdata:
  notification_pgdata:
